Remove previously deprecated code (closes #184) (#188)
* Remove previously deprecated code

Exception: `pre_call` was scheduled for removal in v0.30 but it needs to be
  replaced with some other mechanism, see discussion in #63.

* docs: update changelog

* chore: bump version